// <auto-generated />
using System;
using JobManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250331160606_InitialMigrationSqlServer")]
    partial class InitialMigrationSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobManagement.Domain.Entities.BaseJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("Priority");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.ToTable("BaseJobEntity");

                    b.HasDiscriminator().HasValue("BaseJobEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("JobManagement.Domain.Entities.JobLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("LogType");

                    b.HasIndex("Timestamp");

                    b.ToTable("JobLogs");
                });

            modelBuilder.Entity("JobManagement.Domain.Entities.JobMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageExecutionTimeMs")
                        .HasColumnType("float");

                    b.Property<int>("CompletedJobs")
                        .HasColumnType("int");

                    b.Property<int>("FailedJobs")
                        .HasColumnType("int");

                    b.Property<int>("PendingJobs")
                        .HasColumnType("int");

                    b.Property<int>("RunningJobs")
                        .HasColumnType("int");

                    b.Property<int>("StoppedJobs")
                        .HasColumnType("int");

                    b.Property<double>("SuccessRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalJobs")
                        .HasColumnType("int");

                    b.Property<int>("TotalRetries")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("JobMetrics");
                });

            modelBuilder.Entity("JobManagement.Domain.Entities.MetricSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SnapshotType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotType");

                    b.HasIndex("Timestamp");

                    b.ToTable("MetricSnapshots");
                });

            modelBuilder.Entity("JobManagement.Domain.Entities.QueueMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageWaitTimeMs")
                        .HasColumnType("float");

                    b.Property<int>("HighPriorityJobs")
                        .HasColumnType("int");

                    b.Property<int>("JobsProcessedLastMinute")
                        .HasColumnType("int");

                    b.Property<int>("LowPriorityJobs")
                        .HasColumnType("int");

                    b.Property<int>("RegularPriorityJobs")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalQueueLength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("QueueMetrics");
                });

            modelBuilder.Entity("JobManagement.Domain.Entities.WorkerMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveWorkers")
                        .HasColumnType("int");

                    b.Property<double>("AverageWorkerUtilization")
                        .HasColumnType("float");

                    b.Property<int>("CurrentLoad")
                        .HasColumnType("int");

                    b.Property<int>("IdleWorkers")
                        .HasColumnType("int");

                    b.Property<int>("OfflineWorkers")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int");

                    b.Property<int>("TotalWorkers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("WorkerMetrics");
                });

            modelBuilder.Entity("JobManagement.Domain.Entities.WorkerNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentLoad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LastHeartbeat");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("WorkerNodes");
                });

            modelBuilder.Entity("JobManagement.Infrastructure.Queue.JobQueueState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueueData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobQueueStates");
                });

            modelBuilder.Entity("JobManagement.Domain.Entities.Job", b =>
                {
                    b.HasBaseType("JobManagement.Domain.Entities.BaseJobEntity");

                    b.Property<int>("CurrentRetryCount")
                        .HasColumnType("int");

                    b.Property<string>("ExecutionPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkerNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ScheduledStartTime");

                    b.HasIndex("WorkerNodeId");

                    b.HasDiscriminator().HasValue("Job");
                });

            modelBuilder.Entity("JobManagement.Domain.Entities.JobLog", b =>
                {
                    b.HasOne("JobManagement.Domain.Entities.Job", "Job")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobManagement.Domain.Entities.Job", b =>
                {
                    b.HasOne("JobManagement.Domain.Entities.WorkerNode", "AssignedWorker")
                        .WithMany("AssignedJobs")
                        .HasForeignKey("WorkerNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedWorker");
                });

            modelBuilder.Entity("JobManagement.Domain.Entities.WorkerNode", b =>
                {
                    b.Navigation("AssignedJobs");
                });

            modelBuilder.Entity("JobManagement.Domain.Entities.Job", b =>
                {
                    b.Navigation("ExecutionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
